platform :ios, '9.0'
use_frameworks!
target 'PrincekinKlineFrameDemo' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    
    pod 'PrincekinKlineFrame'
    pod 'Alamofire', '~> 4.7.3'
    pod 'OHHTTPStubs/Swift', '~> 6.1.0'
 end

